<li><a href="add_sale.php">Add Sale</a></li>
<li><a href="manage_sale.php">Manage Sale</a></li>
<li><a href="manage_sale_detail.php">Manage Sale Detail</a></li>
<li><a href="add_customer.php">Add Customer</a></li>
<li><a href="manage_customer.php">Manage Customer</a></li>
<li><a href="add_purchase.php">Add Purchase</a></li>
<li><a href="manage_purchase.php">Manage Purchase</a></li>
<li><a href="manage_purchase_detail.php">Manage Purchase Detail</a></li>
<li><a href="add_supplier.php">Add Supplier</a></li>
<li><a href="manage_supplier.php">Manage Supplier</a></li>
<li><a href="add_product.php">Add Product List</a></li>
<li><a href="manage_product_list.php">Manage Product List</a></li>
<li><a href="add_category.php">Add Category</a></li>
<li><a href="manage_category.php">Manage Category</a></li>
<li><a href="add_customer_payment.php">Add Customer Payment</a></li>
<li><a href="manage_customer_payment.php">Manage Customer Payment</a></li>
<li><a href="add_supplier_payment.php">Add Supplier Payment</a></li>
<li><a href="manage_supplier_payment.php">Manage Supplier Payment</a></li>
<li><a href="add_manufacturer.php">Add Manufacturer</a></li>
<li><a href="manage_manufacturer.php">Manage Manufacturer</a></li>
<li><a href="add_open_stock.php">Add Open Stock</a></li>
<li><a href="manage_open_stock.php">Manage Open Stock</a></li>
<li><a href="add_company_info.php">Add Company Info</a></li>
<li><a href="manage_company_info.php">Manage Company Info</a></li>
<li><a href="add_customer_image.php">Add Customer Image</a></li>
<li><a href="add_sales_return.php">Add Return Sale</a></li>
<li><a href="manage_return_sale.php">Manage Return Sale</a></li>
<li><a href="add_user.php">Add Admin User</a></li>
<li><a href="manage_user.php">Manage Admin User</a></li>